services:
  bot:
    container_name: life-counter-bot
    build: .
    restart: unless-stopped # перезапуск при падении
    env_file:
      - .env # BOT_TOKEN, NOTIFY_TIME, ALLOWED_USER_IDS и др. (НЕ в репо)
    environment:
      TZ: Europe/Moscow # часовой пояс в контейнере
    volumes:
      - ./bot.py:/app/bot.py # горячая правка кода (опц.)
    # networks / logging ⇢ можно добавить позже
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
